# Generated by Django 2.2.3 on 2019-07-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksale', '0002_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Mystery', 'Mystery'), ('Biographies', 'Biographies'), ('Sci-fi', 'Sci-fi and Fantasy'), ('Horror', 'Horror'), ('Kids', 'Kids'), ('Comics', 'Comics'), ('generic', 'generic')], default='generic', max_length=100),
        ),
    ]
